export const ESLINT_RULES = {
  // ESLINT
  'array-callback-return': 'error',
  'no-await-in-loop': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-constructor-return': 'error',
  'no-inner-declarations': ['error', 'both', { blockScopedFunctions: 'disallow' }],
  'no-promise-executor-return': 'error',
  'no-self-compare': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unreachable-loop': 'error',
  'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
  'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
  'require-atomic-updates': ['error', { allowProperties: true }],
  'use-isnan': ['error', { enforceForSwitchCase: true, enforceForIndexOf: true }],

  'accessor-pairs': 'error',
  'arrow-body-style': ['error', 'as-needed'],
  complexity: ['warn', { max: 15, variant: 'classic' }],
  curly: ['error', 'all'],
  'default-case-last': 'error',
  eqeqeq: 'error',
  'grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'guard-for-in': 'error',
  'logical-assignment-operators': ['error', 'always'],
  'max-classes-per-file': ['error', { max: 1, ignoreExpressions: true }],
  'max-depth': ['warn', { max: 4 }],
  // 'max-lines': ['warn', { max: 300, skipBlankLines: true, skipComments: true }], // TODO: consider enabling
  'max-lines-per-function': [
    'warn',
    { max: 60, skipBlankLines: true, skipComments: true, IIFEs: true },
  ],
  'max-nested-callbacks': ['warn', { max: 3 }],
  'max-statements': ['warn', { max: 25 }],
  'no-alert': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-console': ['warn', { allow: ['warn', 'error'] }],
  'no-else-return': ['error', { allowElseIf: false }],
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-implicit-coercion': 'error',
  'no-iterator': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': [
    'error',
    {
      props: true,
      ignorePropertyModificationsFor: ['acc', 'draft', 'state', 'ctx', 'context', 'req', 'res'],
    },
  ],
  'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
  'no-proto': 'error',
  // 'no-restricted-syntax': 'error', // TODO: consider enabling
  'no-return-assign': ['error', 'always'],
  'no-script-url': 'error',
  'no-sequences': ['error', { allowInParentheses: false }],
  'no-undef-init': 'error',
  'no-unneeded-ternary': 'error',
  'no-useless-call': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': ['error', { allowAsStatement: true }],
  // no-warning-comments - here
  'object-shorthand': [
    'error',
    'always',
    { avoidQuotes: true, ignoreConstructors: false, avoidExplicitReturnArrows: false },
  ],
  'one-var': ['error', { var: 'never', let: 'never', const: 'never' }],
  'operator-assignment': ['error', 'always'],
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'warn',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'preserve-caught-error': 'error',
  radix: 'error',
  'symbol-description': 'error',
  yoda: ['error', 'never'],
}
